import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useState } from 'react';
import type { NextPage, GetServerSideProps } from 'next';
const inter = Inter({ subsets: ['latin'] })

interface CatCategory {
  id: number
  name: string
}

interface SearchCatImage {
  breeds: string[]
  categories: CatCategory[]
  id: string
  url: string
  width: number
  height: number
}

type SearchCatImageResponse = SearchCatImage[]

const fetchCatImage = async (): Promise<SearchCatImage> => {
  const res = await fetch("https://api.thecatapi.com/v1/images/search");
  const result = (await res.json()) as SearchCatImageResponse
  return result[0]
}

interface IndexPageProps {
  initialCatImageUrl: string
}

const Home: NextPage<IndexPageProps> = ({ initialCatImageUrl }) => {
  const [catImageUrl, setCatImageUrl] = useState(initialCatImageUrl)

  const handleClick = async () => {
    const image = await fetchCatImage()
    setCatImageUrl(image.url)
  }

  return (
    <>
      <Head>
        <title>Random Cat Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Random Cat Generator</h1>
      <button onClick={handleClick}>Change Cat</button>
      <div style={{ marginTop: 8, maxWidth: '80%' }}>
        <img src={catImageUrl} />
      </div>
    </>
  )
}

export const getServerSideProps: GetServerSideProps<IndexPageProps> = async () => {
  const catImage = await fetchCatImage()
  return {
    props: {
      initialCatImageUrl: catImage.url
    }
  }
}

export default Home